# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='academics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acadId', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('subcatId', models.IntegerField()),
                ('incharge', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
    ]
