# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academics',
            name='id',
        ),
        migrations.AlterField(
            model_name='academics',
            name='acadId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
