# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_auto_20181025_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('sportsId', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('subcatId', models.IntegerField()),
                ('sportname', models.CharField(max_length=45)),
                ('nature', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
    ]
