# Generated by Django 2.0.3 on 2018-10-25 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_auto_20181025_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sports',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.User'),
        ),
    ]
