# Generated by Django 2.0.3 on 2018-10-25 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0006_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='fromdate',
        ),
        migrations.RemoveField(
            model_name='events',
            name='todate',
        ),
    ]
