# Generated by Django 2.0.3 on 2018-10-25 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0007_auto_20181026_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('hostelId', models.AutoField(primary_key=True, serialize=False)),
                ('subcatId', models.IntegerField()),
                ('incharge', models.CharField(max_length=45)),
                ('hostelRoomNo', models.CharField(max_length=6)),
                ('description', models.CharField(max_length=400)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.User')),
            ],
        ),
    ]
