# Generated by Django 2.0.3 on 2018-10-25 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0008_hostel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Others',
            fields=[
                ('othersId', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=400)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.User')),
            ],
        ),
    ]
