# Generated by Django 2.0.3 on 2018-10-04 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('pollId', models.IntegerField(primary_key=True, serialize=False)),
                ('pollContent', models.CharField(max_length=350)),
                ('pollTime', models.DateTimeField(verbose_name='date published')),
                ('pollAgree', models.IntegerField()),
                ('pollDisagree', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userRollNumber', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('userFName', models.CharField(max_length=45)),
                ('userLName', models.CharField(max_length=45)),
                ('userMobileNumber', models.CharField(max_length=10)),
                ('UserUg', models.CharField(max_length=10)),
                ('UserMailId', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='userPollHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApplication.Poll')),
                ('uId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApplication.User')),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='pollCreator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApplication.User'),
        ),
    ]
