# Generated by Django 2.0.3 on 2018-10-04 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApplication', '0006_remove_login_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='paword',
        ),
    ]
