# Generated by Django 2.0.3 on 2018-10-11 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApplication', '0007_auto_20181004_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acadId', models.IntegerField()),
                ('subcatId', models.IntegerField()),
                ('incharge', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=350)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApplication.User')),
            ],
        ),
    ]
