# Generated by Django 2.0.3 on 2018-10-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApplication', '0008_academics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academics',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
