# Generated by Django 2.0.3 on 2018-10-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApplication', '0009_auto_20181011_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='userId',
            field=models.IntegerField(default=20160010049),
            preserve_default=False,
        ),
    ]
