# Generated by Django 2.0.3 on 2018-10-23 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApplication', '0010_login_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='userId',
        ),
    ]
