# Generated by Django 2.0.3 on 2018-10-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApplication', '0011_remove_login_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='latestOtp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
            ],
        ),
    ]
