# Generated by Django 2.0.3 on 2018-10-24 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApplication', '0012_latestotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='userId',
            field=models.ForeignKey(default=20160010049, on_delete=django.db.models.deletion.CASCADE, to='MainApplication.User'),
            preserve_default=False,
        ),
    ]
