# Generated by Django 2.0.3 on 2018-10-24 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApplication', '0013_login_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='latestotp',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MainApplication.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='academics',
            name='subcatId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApplication.Subcategory'),
        ),
        migrations.AlterField(
            model_name='academics',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApplication.User'),
        ),
    ]
