# Generated by Django 2.0.3 on 2018-10-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApplication', '0014_auto_20181024_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academics',
            name='subcatId',
            field=models.CharField(max_length=45),
        ),
    ]
