# Generated by Django 2.0.3 on 2018-10-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userId',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='userRollNumber',
            field=models.CharField(max_length=12),
        ),
    ]
