# Generated by Django 2.0.3 on 2018-10-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApplication', '0003_auto_20181004_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='pollCreator',
        ),
        migrations.RemoveField(
            model_name='userpollhistory',
            name='pId',
        ),
        migrations.RemoveField(
            model_name='userpollhistory',
            name='uId',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='userPollHistory',
        ),
    ]
