# Generated by Django 2.0.3 on 2018-10-04 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MainApplication', '0004_auto_20181004_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userRollNumber', models.IntegerField()),
                ('userFName', models.CharField(max_length=45)),
                ('userLName', models.CharField(max_length=45)),
                ('userMobileNumber', models.CharField(max_length=10)),
                ('UserUg', models.CharField(max_length=10)),
                ('UserMailId', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='login',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApplication.User'),
        ),
    ]
